# Generated by Django 5.0.6 on 2024-12-15 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sosalert',
            options={},
        ),
        migrations.RenameField(
            model_name='sosalert',
            old_name='sent_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='sosalert',
            name='message',
        ),
        migrations.RemoveField(
            model_name='sosalert',
            name='resolved',
        ),
        migrations.AlterField(
            model_name='sosalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL),
        ),
    ]
